=== hmrc/mobile-help-to-save/resources/public/api/conf/1.0/schemas/savings-update.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "properties": {
    "reportStartDate": {
      "type": "string",
      "description": "The start date the update relates to",
      "examples": [
        "2020-01-01"
      ]
    },
    "reportEndDate": {
      "type": "string",
      "description": "The end date the update relates to",
      "examples": [
        "2021-12-31"
      ]
    },
    "accountOpenedYearMonth": {
      "type": "string",
      "description": "The year and month the account was opened",
      "examples": [
        "2018-01"
      ]
    },
    "savingsUpdate": {
      "type": "object",
      "properties": {
        "savedInPeriod": {
          "type": "number",
          "description": "The amount saved during the reporting period",
          "examples": [
            150.00
          ]
        },
        "monthsSaved": {
          "type": "number",
          "description": "The number of months where savings have been debited",
          "examples": [
            3
          ]
        },
        "goalsReached": {
          "type": "object",
          "properties": {
            "currentAmount": {
              "type": "number",
              "description": "The current goal amount set",
              "examples": [
                40.00
              ]
            },
            "numberOfTimesReached": {
              "type": "number",
              "description": "The number of times the savings goal has been met in the reporting period",
              "examples": [
                2
              ]
            }
          }
        },
        "amountEarnedTowardsBonus": {
          "type": "number",
          "description": "The amount earned towards the current bonus in this reporting period",
          "examples": [
            75.00
          ]
        }
      }
    },
    "bonusUpdate": {
      "type": "object",
      "properties": {
        "currentBonusTerm": {
          "type": "string",
          "description": "The current bonus term",
          "examples": [
            "first",
            "second"
          ]
        },
        "monthsUntilBonus": {
          "type": "number",
          "description": "The number of months until the bonus will be paid",
          "examples": [
            6
          ]
        },
        "currentBonus": {
          "type": "number",
          "description": "The current estimated bonus",
          "examples": [
            100.00
          ]
        },
        "highestBalance": {
          "type": "number",
          "description": "The highest the balance has been during the reporting period",
          "examples": [
            300.00
          ]
        },
        "potentialBonusAtCurrentRate": {
          "type": "number",
          "description": "The potential end bonus based on the current rate of saving",
          "examples": [
            350.00
          ]
        },
        "potentialBonusWithFiveMore": {
          "type": "number",
          "description": "The potential end bonus if rate of saving is increased by 5 each month",
          "examples": [
            350.00
          ]
        },
        "maxBonus": {
          "type": "number",
          "description": "The maximum bonus that will be possible to achieve",
          "examples": [
            500.00
          ]
        }
      }
    }
  },
  "required": [
    "reportStartDate",
    "reportEndDate",
    "accountOpenedYearMonth",
    "bonusUpdate"
  ]
}

=== hmrc/mobile-help-to-save/resources/public/api/conf/1.0/examples/savings-update.json
{
  "reportStartDate" : "2021-02-01",
  "reportEndDate" : "2021-06-30",
  "accountOpenedYearMonth" : "2020-02",
  "savingsUpdate" : {
    "savedInPeriod" : 100,
    "monthsSaved" : 4,
    "goalsReached" : {
      "currentAmount" : 25,
      "numberOfTimesReached" : 2
    },
    "amountEarnedTowardsBonus" : 50
  },
  "bonusUpdate" : {
    "currentBonusTerm" : "First",
    "monthsUntilBonus" : 8,
    "currentBonus" : 75,
    "highestBalance" : 200,
    "potentialBonusAtCurrentRate" : 300,
    "potentialBonusWithFiveMore" : 500,
    "maxBonus" : 600
  }
}
